all:
    hosts:
        192.168.0.111
        192.168.0.112
        192.168.0.121
        192.168.0.122
    children:
        webservers:
            hosts:
                192.168.0.111
                192.168.0.112
        dbservers:
            hosts:
                192.168.0.121
                192.168.0.122
